/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#122131",
        "surface-container-low": "#0d1c2d",
        "outline-variant": "#4d4354",
        "surface-tint": "#ddb7ff",
        "on-secondary-fixed": "#001e2c",
        "on-surface": "#d4e4fa",
        "background": "#051424",
        "primary-fixed-dim": "#ddb7ff",
        "secondary-fixed": "#c4e7ff",
        "on-secondary-container": "#00374d",
        "inverse-primary": "#842bd2",
        "surface-container-lowest": "#010f1f",
        "tertiary-container": "#e14ef6",
        "on-primary-container": "#400071",
        "on-primary-fixed": "#2c0051",
        "error-container": "#93000a",
        "on-secondary": "#00354a",
        "surface-variant": "#273647",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#fbabff",
        "tertiary-fixed": "#ffd6fd",
        "on-background": "#d4e4fa",
        "inverse-on-surface": "#233143",
        "on-surface-variant": "#cfc2d6",
        "error": "#ffb4ab",
        "surface-container-highest": "#273647",
        "surface": "#051424",
        "inverse-surface": "#d4e4fa",
        "surface-bright": "#2c3a4c",
        "on-tertiary-container": "#4d0059",
        "on-primary": "#490080",
        "surface-dim": "#051424",
        "secondary": "#7bd0ff",
        "surface-container-high": "#1c2b3c",
        "on-secondary-fixed-variant": "#004c69",
        "outline": "#988d9f",
        "primary-container": "#b76dff",
        "on-tertiary-fixed": "#36003e",
        "secondary-container": "#00a6e0",
        "secondary-fixed-dim": "#7bd0ff",
        "primary": "#ddb7ff",
        "primary-fixed": "#f0dbff",
        "on-primary-fixed-variant": "#6900b3",
        "tertiary": "#fbabff",
        "on-tertiary-fixed-variant": "#7c008e",
        "on-tertiary": "#580065",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-md": "1rem",
        "space-2xs": "0.125rem",
        "margin": "2rem",
        "gutter-lg": "2rem",
        "space-3xl": "4.5rem",
        "space-2xl": "3rem",
        "space-xs": "0.25rem",
        "margin-desktop": "3rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "gutter": "1.5rem",
        "gutter-sm": "1rem",
        "margin-mobile": "1rem",
        "space-sm": "0.5rem",
      },
      fontFamily: {
        "display-hero-mobile": ["'Space Grotesk'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-mono-sm": ["'JetBrains Mono'", "monospace"],
        "headline-lg": ["'Space Grotesk'", "sans-serif"],
        "telemetry-metric": ["'JetBrains Mono'", "monospace"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Space Grotesk'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero": ["'Space Grotesk'", "sans-serif"],
        "headline-sm": ["'Space Grotesk'", "sans-serif"],
        "headline-md": ["'Space Grotesk'", "sans-serif"],
        "title-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl-mobile": ["'Space Grotesk'", "sans-serif"],
        "label-mono-lg": ["'JetBrains Mono'", "monospace"],
        "title-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "title-md": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "label-mono-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "telemetry-metric": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-mono-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "title-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
